###############################################################################
# Makefile
###############################################################################

SRC  = $(wildcard *.c *.cc)
EXE  = $(basename $(SRC))
DAT  = $(EXE:=.dat)
PERF = $(DAT:.dat=.perf)
OUT  = $(EXE:=.out)
KCG  = $(OUT:.out=.kcg)

###############################################################################

CFLAGS = -fopenmp -march=native -O3 -std=c11 -Wall
CXXFLAGS = $(CFLAGS:c11=c++11)
LDFLAGS = -lm -lrt

###############################################################################

all: $(EXE)

clean:
	$(RM) -fv $(EXE) $(DAT) $(TXT) $(OUT) core.* *.dat.old *~

###############################################################################

%.dat: %
	perf record --call-graph dwarf -g -o $@ -- ./$<

%.perf: %.dat
	perf report -g -i $<

###############################################################################

%.out: %
	valgrind --callgrind-out-file=$@ --demangle=yes --dump-instr=yes --tool=callgrind --trace-jump=yes ./$<

%.kcg: %.out
	kcachegrind $< &

###############################################################################

.SUFFIXES:
.SUFFIXES: .c .cc
.PRECIOUS: $(DAT) $(OUT)
.PHONY: all clean
.NOEXPORT:

###############################################################################
